/**
 * \file          t2m_no_flex.c
 *
 * This file is to be used instead of the dynamically generated t2mflex.c if
 * there is no flex program installed or if the installed flex is old [e.g
 * 2.5.35 as opposed to 2.5.39 (!)].
 *
 * \library       midicvt application
 * \author        Chris Ahlstrom and many other authors
 * \date          2014-04-09
 * \updates       2015-08-14
 * \version       $Revision$
 * \license       GNU GPL
 *
 *    By using this file, we don't have to use flex again to generate
 *    t2mflex.c from t2mf.fl and put up with warning messages.
 *
 *    Of course, you will have to manually,reconstruct the current file if
 *    you decided to change the parsing dictated by the t2mf.fl file, or
 *    edit Makefile.am to re-enable the use of flex.
 *
 * \change ca 2015-08-14
 *    We want to support "MThd" as an alternative to "MFile" in parsing
 *    an ASCII file, so we modified t2mf.fl to also return "MTHD" when
 *    encounterding "MThd".  Then we rebuilt this module, which was
 *    quite a task, even with the help of gvimdiff!  Compare the test files
 *    in the "results" directory:  ex1-mthd.asc versus ex1.asc.
 */

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/*
 * C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types.
 */

#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t;
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */

#define YY_USE_CONST

#else   /* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */

#if defined (__STDC__)

#define YY_USE_CONST

#endif   /* defined (__STDC__) */
#endif   /* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */

#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */

#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */

#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */

#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */

#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */

#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */

#ifndef YY_BUF_SIZE
#ifdef __ia64__

/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */

#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the
 * main buffer.
 */

#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

#define YY_LESS_LINENO(n)
#define YY_LINENO_REWIND_TO(ptr)

/* Return all but the first "n" matched characters back to the input stream. */

#define yyless(n) \
   do \
      { \
      /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
      *yy_cp = (yy_hold_char); \
      YY_RESTORE_YY_MORE_OFFSET \
      (yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
      YY_DO_BEFORE_ACTION; /* set up yytext again */ \
      } \
   while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
{
   FILE *yy_input_file;

   char *yy_ch_buf;      /* input buffer */
   char *yy_buf_pos;      /* current position in input buffer */

   /* Size of input buffer in bytes, not including room for EOB
    * characters.
    */

   yy_size_t yy_buf_size;

   /* Number of characters read into yy_ch_buf, not including EOB
    * characters.
    */

   yy_size_t yy_n_chars;

   /* Whether we "own" the buffer - i.e., we know we created it,
    * and can realloc() it to grow it, and should free() it to
    * delete it.
    */

   int yy_is_our_buffer;

   /* Whether this is an "interactive" input source; if so, and
    * if we're using stdio for input, then we want to use getc()
    * instead of fread(), to make sure we stop fetching input after
    * each newline.
    */

   int yy_is_interactive;

   /* Whether we're considered to be at the beginning of a line.
    * If so, '^' rules will be active on the next match, otherwise
    * not.
    */

   int yy_at_bol;

   int yy_bs_lineno; /**< The line count. */
   int yy_bs_column; /**< The column count. */

   /* Whether to try to fill the input buffer when we reach the
    * end of it.
    */

   int yy_fill_buffer;

   int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1

   /* When an EOF's been seen but there's still some text to process
    * then we mark the buffer as YY_EOF_PENDING, to indicate that we
    * shouldn't try reading from the input source any more.  We might
    * still have a bunch of tokens to match, though, because of
    * possible backing-up.
    *
    * When we actually see the EOF, we change the status to "new"
    * (via yyrestart()), so that the user can continue scanning by
    * just pointing yyin at a new input file.
    */

#define YY_BUFFER_EOF_PENDING 2

   };
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */

static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */

#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */

#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */

static char yy_hold_char;
static yy_size_t yy_n_chars;      /* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */

static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;      /* whether we need to initialize */
static int yy_start = 0;   /* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */

static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
   { \
   if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
      YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
   } \
   YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
   }

#define yy_set_bol(at_bol) \
   { \
   if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
      YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
   } \
   YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
   }

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
   (yytext_ptr) = yy_bp; \
   (yytext_ptr) -= (yy_more_len); \
   yyleng = (size_t) (yy_cp - (yytext_ptr)); \
   (yy_hold_char) = *yy_cp; \
   *yy_cp = '\0'; \
   (yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 54
#define YY_END_OF_BUFFER 55
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
   {
   flex_int32_t yy_verify;
   flex_int32_t yy_nxt;
   };
static yyconst flex_int16_t yy_accept[188] =
    {   0,
        0,    0,   44,   44,    0,    0,   55,   53,    1,   49,
       43,   53,   53,   53,   30,   38,   38,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   53,   44,   47,   45,   54,   51,    1,   43,   51,
       41,   51,   51,    0,    2,   40,   38,    0,    0,   42,
       52,   52,   52,   36,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   34,   52,   52,    7,   37,
       52,   11,   52,   52,   52,   52,   52,   52,   52,   52,
       35,   52,    0,   48,   44,   46,   41,   50,   39,   29,
       33,   52,   52,   52,   52,   23,   52,   52,   52,   52,

       52,   52,   52,   52,   52,   52,   52,    8,   10,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   13,   52,   52,   52,   52,   52,   52,   15,
       52,   52,    4,    5,   52,   52,   52,    9,   12,   52,
       52,   52,   52,   52,   52,   17,   52,   52,   52,   52,
       52,   52,   21,   32,   52,    3,   31,   10,   52,   24,
       52,   28,   14,   26,   52,   52,   52,   52,   52,   25,
       22,   52,   52,   52,    6,   52,   52,   52,   19,   16,
       27,   19,   52,   52,   18,   20,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    6,    1,    1,    1,    1,
        1,    1,    7,    1,    7,    1,    8,    9,   10,   10,
       10,   10,   10,   10,   10,   10,   11,    8,    1,    1,
       12,    1,    1,    1,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   35,
        1,   38,    1,    1,    1,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   55,   56,   57,   58,   59,   60,   35,   61,
       62,   35,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[197] =
    {   0,
        0,    0,   60,   62,  100,    0,   96, 1843, 1843, 1843,
     1843,   92,    0,   58, 1843,  154,   61,  161,  169,  213,
       68,  177,  187,  201,  268,  238,  283,  331,  383,  429,
      257,   78,    0, 1843, 1843,    0, 1843, 1843, 1843,   73,
        0,    0,   80,   71, 1843,    0,   75,    0,   78,   81,
      247,  309,  323, 1843,  487,  347,  314,  341,  360,  385,
      388,  425,  400,  449,  487, 1843,  474,  477,  401, 1843,
      493,  439,  526,  532,  539,  507,  544,  545,  552,  551,
     1843,  596,   91, 1843,    0, 1843, 1843,    0,    0,  598,
     1843,  603,  600,  600,  608,  610,  648,  650,  652,  673,

      697,  685,  704,  702,  706,  740,  714,  737,  754,  747,
      756,  768,  792,  804,  806,  780,  812,  816,  832,  833,
      829,  187,  859,  848,  856,  875,  869,  885,  890,  888,
      900,  908,  922,  932,  940,  937,  953,  957,  965,  985,
      978,  990,  958, 1002, 1015, 1023, 1033, 1045, 1037, 1049,
     1076, 1081, 1047, 1094, 1091, 1101, 1104, 1111, 1094, 1129,
     1127, 1141, 1147, 1149, 1155, 1178, 1156, 1196, 1184, 1201,
     1209, 1202, 1218, 1230, 1239, 1219, 1248, 1248, 1267, 1270,
     1276, 1284, 1288, 1288, 1305, 1323, 1843, 1377, 1439, 1492,
     1534, 1596, 1658, 1712, 1744, 1798

    } ;

static yyconst flex_int16_t yy_def[197] =
    {   0,
      187,    1,  188,  188,  187,    5,  187,  187,  187,  187,
      187,  189,  190,  187,  187,  187,  187,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,   29,
       28,  187,  192,  187,  187,  193,  187,  187,  187,  189,
      194,  195,  187,  189,  187,  190,  187,  196,  187,  187,
      191,  191,  191,  187,  191,   55,   29,   55,   29,   30,
       30,   55,   30,   55,   30,  187,   55,   55,   55,  187,
       30,   55,   55,   55,   55,   55,   55,   29,   29,   55,
      187,   55,  187,  187,  192,  187,  187,  195,  196,   55,
      187,   55,   30,   55,   29,   55,   55,   55,   30,   55,

       55,   55,   55,   55,   55,   55,   30,   55,   55,   29,
       30,   55,   55,   55,   55,   30,   55,   55,   30,   30,
       55,   55,   55,   30,   30,   30,   55,   30,   30,   55,
       30,   30,   55,   55,   55,   29,   55,   55,   55,   55,
       55,   55,   29,   55,   55,   55,   55,   55,   55,   30,
       55,   55,   55,   55,   30,   55,   55,   55,   29,   55,
       29,   55,   55,   55,   30,   55,   29,   55,   55,   55,
       55,   29,   55,   55,   55,   29,   55,   29,   55,   55,
       55,   55,   55,   29,   55,   55,    0,  187,  187,  187,
      187,  187,  187,  187,  187,  187

    } ;

static yyconst flex_int16_t yy_nxt[1906] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       17,    8,   18,   19,   20,   19,   19,   19,   19,   21,
       22,   21,   23,   24,   25,   26,   27,   28,   21,   21,
       29,   30,   21,   31,   21,   21,   21,   32,   18,   19,
       20,   19,   19,   19,   19,   21,   22,   21,   23,   24,
       25,   26,   27,   28,   21,   21,   29,   30,   21,   31,
       21,   21,   34,   35,   34,   35,   47,   47,   47,   47,
       47,   47,  187,   45,  187,   45,  187,  187,  187,   83,
       84,   83,   84,   47,   47,   47,   50,   50,   50,   50,
       50,   50,   83,   84,   45,  187,  187,   36,  187,   36,

       37,   38,   10,   39,   40,   37,   37,   37,   41,   41,
       41,   37,   41,   41,   41,   41,   41,   41,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   43,   41,   41,
       41,   41,   41,   41,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   47,   47,   47,   49,  187,   49,  187,   50,
       50,   50,  187,   49,   52,   49,  187,   50,   50,   50,
      187,  187,   52,  187,  187,  187,  187,  187,  187,   48,
       53,  187,  187,  187,  187,  187,  187,  187,  187,   51,

       52,  187,   58,   59,  187,  187,  187,  187,   52,  187,
      187,  187,  187,  187,   48,  187,   53,   49,  187,   49,
      187,   50,   50,   50,   54,   51,   52,  187,   58,   59,
      187,  187,   55,  187,  187,  187,  187,   60,  187,   56,
      187,  187,  187,  187,  187,   57,  187,  187,  187,   66,
      187,  187,   52,  187,  187,  187,  187,  187,   55,  187,
      187,  187,   60,  187,   67,   56,  187,  187,   81,   82,
       51,   57,  187,  187,  187,  187,  187,  187,  187,  187,
       61,  187,  187,   82,   62,   63,   51,  187,   64,  187,
       67,  187,  187,  187,  187,   82,   51,  187,  187,   65,

       68,  187,  187,  187,  187,  187,   61,  187,   69,   82,
       62,   63,   51,  187,   64,  187,  187,   50,   50,   50,
      187,  187,  187,  187,  187,   65,   68,  187,  187,  187,
       96,  187,  187,  187,   69,  187,   90,  187,   51,  187,
      187,  187,   70,   71,   72,  187,  187,  187,  187,  187,
       51,  187,  187,   51,  187,  187,   96,   73,  187,   51,
       74,  187,   90,  187,   51,  187,  187,  187,   51,   71,
       72,   97,   94,  187,   95,   51,   51,  187,  187,   51,
      187,  187,  187,   73,   51,   51,   74,  187,  187,  187,
      187,  187,  187,  187,   51,  187,   98,   97,   94,   75,

       95,   51,   51,  187,   51,   51,  187,   76,   51,  100,
       51,  187,  187,   51,   99,  187,   51,  101,  187,   77,
      103,   98,  187,  187,  187,   75,  187,   51,   51,   51,
       51,   51,  187,   76,   51,  100,  187,   51,  187,   51,
       99,  187,   51,  101,   77,   78,  103,  187,  187,   79,
      187,   51,   51,   51,   51,   51,  102,  187,   80,  187,
      187,   51,  187,   51,  187,   51,   51,  187,  187,  187,
      187,   78,  187,  187,  104,   79,   51,   51,   51,   51,
      187,  187,  102,  187,   80,  187,   51,   51,  187,   51,
       51,  187,   51,  187,  108,  187,  187,  187,   91,   92,

      104,   51,   51,   51,   51,  107,  105,   51,  187,   51,
      187,  187,   51,   51,   93,   51,  106,  187,  187,   51,
      108,  187,  109,  187,  187,   92,  187,   51,  187,   51,
       51,  107,  105,   51,  115,   51,  187,  187,   51,   51,
       93,  187,  106,  187,   51,   51,  112,  187,  109,  110,
      187,   51,  187,  111,  187,  187,   51,  187,  113,   51,
      115,   51,  187,   51,   51,  187,   51,  114,   51,  117,
       51,   51,  112,  120,  116,  110,  119,   51,   51,  111,
      118,   51,   51,  187,  113,   51,  187,   51,   51,   51,
      187,  187,   51,  114,   51,  117,  187,   51,  187,  120,

      116,  187,  119,  187,   51,  118,   51,  187,   51,  187,
       51,   54,   51,   51,  187,   51,   51,  187,  187,  121,
       51,  187,   51,   51,   51,   51,  187,   51,  122,  123,
       51,  187,   51,  187,   51,  187,   51,   51,   51,  187,
      187,   51,   51,  187,  124,  121,   51,  187,   51,   51,
       51,   51,  187,   51,  122,  123,   51,  187,   51,  187,
       51,  187,   51,   51,  187,  187,  187,  187,   51,  124,
      187,  187,  127,  187,  187,   51,  187,   51,  187,  125,
      126,   51,  187,  187,  187,   51,   51,  187,   51,  187,
      187,  187,  187,  187,   51,  187,  187,  130,  127,  128,

       51,   51,  187,   51,  187,  125,  126,   51,  187,   51,
      187,   51,   51,  187,   51,  187,   51,  187,   51,  129,
      187,  133,  187,  130,   51,  128,   51,  131,  132,   51,
      135,   51,  187,   51,   51,   51,  187,  187,   51,  187,
       51,  187,   51,   51,   51,  129,  187,  133,  187,   51,
       51,  187,   51,  131,  132,   51,  135,   51,  187,   51,
       51,  187,  134,   51,   51,  187,  136,   51,  187,   51,
      187,   51,   51,  187,  187,   51,   51,  187,   51,  187,
       51,   51,  187,  137,  187,  138,  187,  139,  134,   51,
       51,  187,  136,   51,  187,   51,  144,   51,   51,  187,

       51,  187,   51,  187,   51,  187,   51,   51,  137,   51,
      140,  138,  187,  139,  187,  187,   51,  187,   51,   51,
      187,   51,  144,  187,   51,  187,   51,  187,   51,  141,
       51,   51,  187,   51,  142,   51,  140,  143,  187,  145,
       81,   51,   51,   51,   51,   51,  187,  146,  147,  148,
       51,  187,   51,   51,   51,  141,   51,   51,  149,   51,
      142,   51,   51,  143,   51,  145,  187,   51,   51,   51,
      187,   51,   51,  146,  147,  148,   51,  150,   51,   51,
      187,   51,   51,  153,  149,  151,   51,   51,   51,  187,
       51,   51,  187,  187,   51,  152,   51,   51,   51,  187,

       51,   51,   51,  150,   51,   51,  155,   51,  187,  153,
       51,  151,   51,  187,  154,   51,  156,   51,  187,   51,
       51,  152,   51,  187,   51,  187,   51,   51,   51,   51,
       51,   51,  155,  187,   51,  187,   51,  157,  187,  187,
      154,   51,  156,  187,   51,   51,   51,  187,  187,   51,
       51,   66,   51,   51,   51,   51,  187,  187,  187,   51,
       51,  158,  187,  157,  187,   51,  187,   51,  187,   51,
       51,  187,  187,   51,  162,   51,  187,   51,   51,   51,
      111,  187,   51,  187,   51,   51,  187,  158,  187,  187,
      159,   51,   51,   51,   51,   51,   70,   51,   51,  112,

      162,  187,   51,   51,  187,   51,  111,  160,   51,  187,
       51,  187,   51,  187,   51,  187,  159,  161,   51,   51,
      187,  187,  187,   51,  187,  112,  187,   51,   51,   51,
      187,   51,  187,  160,  187,   51,  187,  163,   51,  187,
       51,  164,   51,  161,  187,   51,  187,  187,  187,  167,
       51,  187,  187,   51,  187,   51,  187,   51,  187,   51,
       51,   51,  163,  165,   51,   51,  187,  164,   51,  168,
      166,   51,   51,  187,   51,  167,   51,  187,   51,  187,
      187,  187,  187,   51,  187,   51,   51,  187,   51,  165,
       51,   51,  187,   51,  187,  168,  166,  187,   51,  170,

       51,  169,  187,   51,   51,  187,   51,   51,   51,  187,
       51,   51,  187,   51,   51,  187,   51,  187,  172,   51,
      171,   51,  187,   51,  187,  170,  187,  169,   51,   51,
       51,   51,   51,   51,   51,  187,   51,   51,   51,   51,
      187,   51,   51,  173,  172,  187,  171,   51,  187,   51,
      187,   51,  187,   51,   51,   51,   51,   51,  187,   51,
      187,   51,  187,   51,   51,  187,  187,   51,   51,  173,
      187,   51,   51,  187,   51,  174,   51,   51,  187,   51,
      176,  187,   51,  187,   51,   51,  187,   51,   51,  187,
       51,  187,   51,  175,   51,  187,  178,   51,   51,  187,

       51,  174,   51,  187,  187,   51,  176,  187,   51,  187,
       51,   51,  187,   51,  177,  187,   51,   51,  179,  175,
      187,   51,  178,   51,  187,  187,   51,  187,   51,  187,
       51,   51,  180,  187,   51,  182,   51,   51,   51,   51,
      177,  187,   51,   51,  179,   51,  187,   51,  181,   51,
      187,   51,   51,  187,   51,   51,   51,   51,  180,  187,
       51,  182,   51,   51,   51,  187,   51,  183,   51,   51,
      187,   51,  184,  187,  181,   51,  187,   51,  187,   51,
       51,  187,   51,   51,   51,  187,   51,  187,   51,  187,
       51,  187,   51,  183,   51,  187,   51,   51,  184,  187,

       51,   51,  187,   51,  186,   51,  187,  187,   51,   51,
      187,   51,   51,  187,   51,   51,  187,   51,  187,  185,
       51,  187,   51,   51,   51,  187,   51,  187,  187,   51,
      186,  187,   51,  187,  187,   51,  187,   51,   51,  187,
      187,   51,  187,   51,  187,  185,  187,  187,  187,   51,
       51,  187,  187,  187,  187,  187,  187,  187,   51,  187,
      187,   51,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,   51,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,

       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,

       44,   46,  187,  187,   46,   46,   46,   46,   46,   46,
       46,   46,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
       46,   46,   46,   46,   46,   46,   46,   46,   51,  187,
       51,  187,   51,   51,   51,  187,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,  187,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   85,   85,  187,  187,

       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,  187,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,

       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       87,   87,   87,  187,   87,   87,   87,   87,   87,   87,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
       87,   87,   87,   87,   87,   87,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,  187,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,

       88,   88,   88,   88,   88,   88,   89,   89,   89,  187,
       89,   89,   89,   89,   89,   89,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,   89,   89,   89,   89,
       89,   89,    7,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,

      187,  187,  187,  187,  187
    } ;

static yyconst flex_int16_t yy_chk[1906] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    4,    4,   14,   14,   14,   17,
       17,   17,   21,   44,   21,   40,   21,   21,   21,   32,
       32,   43,   43,   47,   47,   47,   49,   49,   49,   50,
       50,   50,   83,   83,   12,    7,    0,    3,    0,    4,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,   16,   16,   16,   18,    0,   18,    0,   18,
       18,   18,    0,   19,   18,   19,    0,   19,   19,   19,
        0,   22,   19,   22,    0,   22,   22,   22,    0,   16,
       18,   23,    0,   23,    0,   23,   23,   23,  122,  122,

       18,    0,   22,   23,    0,   24,    0,   24,   19,   24,
       24,   24,    0,    0,   16,    0,   18,   20,    0,   20,
        0,   20,   20,   20,   20,  122,   20,    0,   22,   23,
        0,    0,   20,    0,    0,    0,    0,   24,    0,   20,
        0,    0,   26,    0,   26,   20,   26,   26,   26,   26,
        0,   51,   20,   51,    0,   51,   51,   51,   20,    0,
        0,    0,   24,    0,   26,   20,    0,    0,   31,   31,
       31,   20,   25,    0,   25,    0,   25,   25,   25,    0,
       25,    0,    0,   31,   25,   25,   31,   27,   25,   27,
       26,   27,   27,   27,    0,   31,   31,    0,    0,   25,

       27,    0,    0,    0,    0,    0,   25,    0,   27,   31,
       25,   25,   31,   52,   25,   52,    0,   52,   52,   52,
        0,    0,    0,    0,    0,   25,   27,   53,    0,   53,
       57,   53,   53,   53,   27,   28,   53,   28,   57,   28,
       28,   28,   28,   28,   28,    0,    0,    0,    0,    0,
       57,    0,   58,   58,    0,    0,   57,   28,   56,   56,
       28,    0,   53,    0,   57,    0,    0,    0,   58,   28,
       28,   58,   56,    0,   56,   57,   59,    0,    0,   58,
        0,    0,    0,   28,   59,   56,   28,   29,    0,   29,
        0,   29,   29,   29,   58,    0,   59,   58,   56,   29,

       56,   60,   59,    0,   61,   60,    0,   29,   61,   61,
       59,    0,   69,   69,   60,    0,   63,   61,    0,   29,
       63,   59,    0,    0,    0,   29,    0,   60,   69,   63,
       61,   60,    0,   29,   61,   61,   62,   62,    0,   69,
       60,    0,   63,   61,   29,   30,   63,    0,    0,   30,
       72,   72,   62,   30,   69,   63,   62,    0,   30,    0,
       64,   64,    0,   62,    0,   30,   72,    0,    0,    0,
        0,   30,    0,    0,   64,   30,   64,   72,   62,   30,
        0,    0,   62,    0,   30,   67,   67,   64,   68,   68,
       30,   55,   72,   55,   68,   55,   55,   55,   55,   55,

       64,   67,   64,   65,   68,   67,   65,   65,    0,   71,
        0,    0,   67,   71,   55,   68,   65,    0,   76,   76,
       68,    0,   71,    0,    0,   55,    0,   67,    0,   65,
       68,   67,   65,   65,   76,   71,    0,   73,   73,   71,
       55,    0,   65,   74,   74,   76,   74,    0,   71,   73,
       75,   75,    0,   73,    0,   77,   77,    0,   74,   74,
       76,   78,   80,   80,   73,    0,   75,   75,   79,   78,
       74,   77,   74,   80,   77,   73,   79,   75,   80,   73,
       78,   78,   77,    0,   74,   74,    0,   78,   79,   80,
        0,    0,   75,   75,   79,   78,    0,   77,    0,   80,

       77,    0,   79,    0,   80,   78,   78,   82,   82,   90,
       90,   94,   94,   79,   92,   92,   93,    0,    0,   82,
       93,   96,   96,   82,   95,   90,    0,   94,   92,   93,
       92,    0,   95,    0,   82,    0,   90,   96,   94,    0,
        0,   92,   93,    0,   95,   82,   93,    0,   96,   82,
       95,   90,    0,   94,   92,   93,   92,    0,   95,   97,
       97,   98,   98,   96,    0,    0,    0,    0,   99,   95,
        0,    0,   99,    0,    0,   97,    0,   98,    0,   97,
       98,   99,    0,    0,  100,  100,   97,    0,   98,    0,
        0,    0,    0,    0,   99,    0,  102,  102,   99,  100,

      100,   97,    0,   98,    0,   97,   98,   99,  101,  101,
        0,  100,  102,  104,  104,  103,  103,  105,  105,  101,
        0,  105,    0,  102,  101,  100,  100,  103,  104,  104,
      107,  103,    0,  105,  107,  101,    0,    0,  102,    0,
      104,    0,  103,  107,  105,  101,    0,  105,  108,  108,
      101,  106,  106,  103,  104,  104,  107,  103,    0,  105,
      107,    0,  106,  110,  108,  109,  109,  106,    0,  107,
        0,  110,  111,    0,    0,  108,  111,    0,  106,  112,
      112,  109,    0,  110,    0,  111,    0,  112,  106,  110,
      108,    0,  109,  106,    0,  112,  116,  110,  111,    0,

      116,    0,  111,  113,  113,    0,  112,  109,  110,  116,
      113,  111,    0,  112,    0,  114,  114,  115,  115,  113,
        0,  112,  116,  117,  117,    0,  116,  118,  118,  114,
      113,  114,    0,  115,  114,  116,  113,  115,    0,  117,
      121,  121,  114,  118,  115,  113,    0,  118,  119,  120,
      117,    0,  119,  120,  118,  114,  121,  114,  120,  115,
      114,  119,  120,  115,  124,  117,    0,  121,  124,  118,
      123,  123,  125,  118,  119,  120,  125,  124,  119,  120,
      127,  127,  121,  127,  120,  125,  123,  119,  120,    0,
      124,  126,    0,    0,  124,  126,  127,  123,  125,  130,

      130,  128,  125,  124,  126,  128,  129,  127,    0,  127,
      129,  125,  123,    0,  128,  130,  131,  126,    0,  129,
      131,  126,  127,    0,  132,    0,  130,  128,  132,  131,
      126,  128,  129,  133,  133,    0,  129,  132,    0,    0,
      128,  130,  131,  134,  134,  129,  131,    0,    0,  133,
      132,  135,  135,  136,  132,  131,    0,    0,    0,  134,
      133,  136,    0,  132,  137,  137,    0,  135,  138,  138,
      134,    0,    0,  136,  143,  133,  139,  139,  135,  136,
      137,    0,  143,    0,  138,  134,    0,  136,    0,  141,
      141,  137,  139,  135,  143,  138,  140,  140,  136,  140,

      143,  142,  142,  139,    0,  141,  137,  141,  143,    0,
      138,    0,  140,  144,  144,    0,  141,  142,  139,  143,
        0,    0,    0,  140,    0,  140,  145,  145,  142,  144,
        0,  141,    0,  141,  146,  146,    0,  144,  140,    0,
      144,  145,  145,  142,  147,  147,    0,    0,  149,  149,
      146,    0,    0,  145,    0,  144,  148,  148,  153,  153,
      147,  146,  144,  147,  149,  150,    0,  145,  145,  150,
      148,  147,  148,    0,  153,  149,  146,    0,  150,    0,
        0,    0,    0,  148,    0,  153,  147,  151,  151,  147,
      149,  150,  152,  152,    0,  150,  148,    0,  148,  152,

      153,  151,    0,  151,  150,  154,  154,  155,  152,    0,
      159,  155,  156,  156,  151,  157,  157,    0,  159,  152,
      155,  154,  158,  158,    0,  152,    0,  151,  156,  151,
      159,  157,  154,  155,  152,    0,  159,  155,  158,  156,
      160,  160,  157,  161,  159,    0,  155,  154,    0,  158,
        0,  161,  162,  162,  156,  159,  160,  157,  163,  163,
      164,  164,    0,  161,  158,    0,    0,  160,  162,  161,
        0,  165,  167,    0,  163,  165,  164,  161,    0,  162,
      167,    0,  160,    0,  165,  163,    0,  164,  161,  166,
      166,    0,  167,  166,  162,  169,  169,  165,  167,    0,

      163,  165,  164,    0,    0,  166,  167,  168,  168,    0,
      165,  169,  170,  170,  168,    0,  166,  167,  172,  166,
      171,  171,  169,  168,    0,    0,  172,    0,  170,  173,
      173,  166,  173,    0,  168,  176,  171,  169,  172,  170,
      168,  174,  174,  176,  172,  173,    0,  171,  174,  168,
      175,  175,  172,    0,  170,  176,  173,  174,  173,  177,
      177,  176,  171,  172,  178,    0,  175,  177,  174,  176,
        0,  173,  178,    0,  174,  177,    0,  175,  179,  179,
      176,  180,  180,  174,  178,    0,  177,  181,  181,    0,
      178,    0,  175,  177,  179,  182,  182,  180,  178,  183,

      183,  177,    0,  181,  184,  179,    0,    0,  180,  178,
        0,  182,  184,    0,  181,  183,  185,  185,    0,  183,
      179,    0,  182,  180,  184,    0,  183,    0,    0,  181,
      184,    0,  185,    0,  186,  186,    0,  182,  184,    0,
        0,  183,    0,  185,    0,  183,    0,    0,    0,  184,
      186,    0,    0,    0,    0,    0,    0,    0,  185,    0,
        0,  186,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  186,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,

      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,

      189,  190,    0,    0,  190,  190,  190,  190,  190,  190,
      190,  190,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      190,  190,  190,  190,  190,  190,  190,  190,  191,    0,
      191,    0,  191,  191,  191,    0,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,    0,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  192,  192,    0,    0,

      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,    0,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,

      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      194,  194,  194,    0,  194,  194,  194,  194,  194,  194,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      194,  194,  194,  194,  194,  194,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,    0,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,

      195,  195,  195,  195,  195,  195,  196,  196,  196,    0,
      196,  196,  196,  196,  196,  196,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  196,  196,  196,  196,
      196,  196,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,

      187,  187,  187,  187,  187
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */

#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
/* line 1 "t2mf.fl" */
/* $Id: t2mf.fl,v 1.3 1991/11/15 19:31:00 piet Rel $ */
#define YY_NO_INPUT 1
/* #line 8 "t2mf.fl" */

#include <midicvt_base.h>
#include <t2mf.h>

#ifdef NO_YYLENG_VAR
yy_size_t yylength;
#define YY_USER_ACTION   yylength = yyleng
#endif

int do_hex = 0;
int eol_seen = 0;
int lineno = 1;
extern long yyval;
extern long bankno (char *s, int n);

#define INITIAL 0
#define QUOTE 1
#define HEX 2

#ifndef YY_NO_UNISTD_H

/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */

#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
   if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
      { \
      int c = '*'; \
      size_t n; \
      for ( n = 0; n < max_size && \
              (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
         buf[n] = (char) c; \
      if ( c == '\n' ) \
         buf[n++] = (char) c; \
      if ( c == EOF && ferror( yyin ) ) \
         YY_FATAL_ERROR( "input in flex scanner failed" ); \
      result = n; \
      } \
   else \
      { \
      errno=0; \
      while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
         { \
         if( errno != EINTR) \
            { \
            YY_FATAL_ERROR( "input in flex scanner failed" ); \
            break; \
            } \
         errno=0; \
         clearerr(yyin); \
         } \
      }\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
   YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
   register yy_state_type yy_current_state;
   register char *yy_cp, *yy_bp;
   register int yy_act;

   if ( !(yy_init) )
      {
      (yy_init) = 1;

#ifdef YY_USER_INIT
      YY_USER_INIT;
#endif

      if ( ! (yy_start) )
         (yy_start) = 1;   /* first start state */

      if ( ! yyin )
         yyin = stdin;

      if ( ! yyout )
         yyout = stdout;

      if ( ! YY_CURRENT_BUFFER ) {
         yyensure_buffer_stack ();
         YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
      }

      yy_load_buffer_state( );
      }

   {
  if (do_hex)
  {
     BEGIN(HEX);
     do_hex = 0;
  }
  eol_seen = 0;

   while ( 1 )      /* loops until end-of-file is reached */
      {
      (yy_more_len) = 0;
      if ( (yy_more_flag) )
         {
         (yy_more_len) = (yy_c_buf_p) - (yytext_ptr);
         (yy_more_flag) = 0;
         }
      yy_cp = (yy_c_buf_p);

      /* Support of yytext. */
      *yy_cp = (yy_hold_char);

      /* yy_bp points to the position in yy_ch_buf of the start of
       * the current run.
       */
      yy_bp = yy_cp;

      yy_current_state = (yy_start);
yy_match:
      do
         {
         register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
         if ( yy_accept[yy_current_state] )
            {
            (yy_last_accepting_state) = yy_current_state;
            (yy_last_accepting_cpos) = yy_cp;
            }
         while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
            {
            yy_current_state = (int) yy_def[yy_current_state];
            }
         yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
         ++yy_cp;
         }
      while ( yy_base[yy_current_state] != 1843 );

yy_find_action:
      yy_act = yy_accept[yy_current_state];
      if ( yy_act == 0 )
         { /* have to back up */
         yy_cp = (yy_last_accepting_cpos);
         yy_current_state = (yy_last_accepting_state);
         yy_act = yy_accept[yy_current_state];
         }

      YY_DO_BEFORE_ACTION;

do_action:   /* This label is used only to access EOF actions. */

      switch ( yy_act )
   { /* beginning of action switch */
         case 0: /* must back up */
         /* undo the effects of YY_DO_BEFORE_ACTION */
         *yy_cp = (yy_hold_char);
         yy_cp = (yy_last_accepting_cpos);
         yy_current_state = (yy_last_accepting_state);
         goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 37 "t2mf.fl"
/* skip whitespace */;
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 38 "t2mf.fl"
/* skip comment */ lineno++;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 40 "t2mf.fl"
return MTHD;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 41 "t2mf.fl"
return MTHD;   /* Handle MThd like MFile */
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 42 "t2mf.fl"
return MTRK;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 43 "t2mf.fl"
return TRKEND;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 45 "t2mf.fl"
return ON;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 46 "t2mf.fl"
return OFF;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 47 "t2mf.fl"
return POPR;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 48 "t2mf.fl"
return PAR;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 49 "t2mf.fl"
return PB;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 50 "t2mf.fl"
return PRCH;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 51 "t2mf.fl"
return CHPR;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 52 "t2mf.fl"
return SYSEX;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 53 "t2mf.fl"
return META;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 54 "t2mf.fl"
return SEQSPEC;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 55 "t2mf.fl"
return TEXT;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 56 "t2mf.fl"
return COPYRIGHT;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 57 "t2mf.fl"
return SEQNAME;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 58 "t2mf.fl"
return INSTRNAME;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 59 "t2mf.fl"
return LYRIC;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 60 "t2mf.fl"
return MARKER;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 61 "t2mf.fl"
return CUE;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 62 "t2mf.fl"
return SEQNR;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 63 "t2mf.fl"
return KEYSIG;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 64 "t2mf.fl"
return TEMPO;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 65 "t2mf.fl"
return TIMESIG;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 66 "t2mf.fl"
return SMPTE;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 67 "t2mf.fl"
return ARB;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 68 "t2mf.fl"
return '/';
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 70 "t2mf.fl"
return MINOR;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 71 "t2mf.fl"
return MAJOR;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 73 "t2mf.fl"
return CH;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 74 "t2mf.fl"
return NOTE;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 75 "t2mf.fl"
return VAL;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 76 "t2mf.fl"
return CON;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 77 "t2mf.fl"
return PROG;
	YY_BREAK
/* Conflicting printf specifications, warnings inevitable. */
case 38:
YY_RULE_SETUP
#line 81 "t2mf.fl"
sscanf(yytext, "%ld", &yyval); return INT;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 82 "t2mf.fl"
sscanf(yytext+2, "%lx", (long unsigned int *) &yyval); return INT;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 83 "t2mf.fl"
yyval = bankno(yytext+1, yyleng-1); return INT;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 84 "t2mf.fl"
sscanf(yytext, "%lx", (long unsigned int *) &yyval); return INT;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 86 "t2mf.fl"
return NOTEVAL;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 88 "t2mf.fl"
BEGIN (QUOTE);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 89 "t2mf.fl"
yymore();
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 90 "t2mf.fl"
BEGIN (0); return STRING;
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 91 "t2mf.fl"
yymore();
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 92 "t2mf.fl"
{
                        error("unterminated string");
                        lineno++; eol_seen++; BEGIN(0); return EOL;
                     }
   YY_BREAK
case YY_STATE_EOF(QUOTE):
#line 96 "t2mf.fl"
error("EOF in string"); return EOF;
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 98 "t2mf.fl"
lineno++;
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 99 "t2mf.fl"
lineno++; eol_seen++; BEGIN(0); return EOL;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 101 "t2mf.fl"
BEGIN (0); return ERR;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 102 "t2mf.fl"
BEGIN (0); return ERR;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 103 "t2mf.fl"
return ERR;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 104 "t2mf.fl"
return ERR;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(HEX):
#line 106 "t2mf.fl"
return EOF;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 108 "t2mf.fl"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1531 "lex.yy.c"

   case YY_END_OF_BUFFER:
      {
      /* Amount of text matched not including the EOB char. */
      int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

      /* Undo the effects of YY_DO_BEFORE_ACTION. */
      *yy_cp = (yy_hold_char);
      YY_RESTORE_YY_MORE_OFFSET

      if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
         {
         /* We're scanning a new file or input source.  It's
          * possible that this happened because the user
          * just pointed yyin at a new source and called
          * yylex().  If so, then we have to assure
          * consistency between YY_CURRENT_BUFFER and our
          * globals.  Here is the right place to do so, because
          * this is the first action (other than possibly a
          * back-up) that will match for the new input source.
          */
         (yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
         YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
         YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
         }

      /* Note that here we test for yy_c_buf_p "<=" to the position
       * of the first EOB in the buffer, since yy_c_buf_p will
       * already have been incremented past the NUL character
       * (since all states make transitions on EOB to the
       * end-of-buffer state).  Contrast this with the test
       * in input().
       */
      if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
         { /* This was really a NUL. */
         yy_state_type yy_next_state;

         (yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

         yy_current_state = yy_get_previous_state(  );

         /* Okay, we're now positioned to make the NUL
          * transition.  We couldn't have
          * yy_get_previous_state() go ahead and do it
          * for us because it doesn't know how to deal
          * with the possibility of jamming (and we don't
          * want to build jamming into it because then it
          * will run more slowly).
          */

         yy_next_state = yy_try_NUL_trans( yy_current_state );

         yy_bp = (yytext_ptr) + YY_MORE_ADJ;

         if ( yy_next_state )
            {
            /* Consume the NUL. */
            yy_cp = ++(yy_c_buf_p);
            yy_current_state = yy_next_state;
            goto yy_match;
            }

         else
            {
            yy_cp = (yy_c_buf_p);
            goto yy_find_action;
            }
         }

      else switch ( yy_get_next_buffer(  ) )
         {
         case EOB_ACT_END_OF_FILE:
            {
            (yy_did_buffer_switch_on_eof) = 0;

            if ( yywrap( ) )
               {
               /* Note: because we've taken care in
                * yy_get_next_buffer() to have set up
                * yytext, we can now set up
                * yy_c_buf_p so that if some total
                * hoser (like flex itself) wants to
                * call the scanner after we return the
                * YY_NULL, it'll still work - another
                * YY_NULL will get returned.
                */
               (yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

               yy_act = YY_STATE_EOF(YY_START);
               goto do_action;
               }

            else
               {
               if ( ! (yy_did_buffer_switch_on_eof) )
                  YY_NEW_FILE;
               }
            break;
            }

         case EOB_ACT_CONTINUE_SCAN:
            (yy_c_buf_p) =
               (yytext_ptr) + yy_amount_of_matched_text;

            yy_current_state = yy_get_previous_state(  );

            yy_cp = (yy_c_buf_p);
            yy_bp = (yytext_ptr) + YY_MORE_ADJ;
            goto yy_match;

         case EOB_ACT_LAST_MATCH:
            (yy_c_buf_p) =
            &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

            yy_current_state = yy_get_previous_state(  );

            yy_cp = (yy_c_buf_p);
            yy_bp = (yytext_ptr) + YY_MORE_ADJ;
            goto yy_find_action;
         }
      break;
      }

   default:
      YY_FATAL_ERROR(
         "fatal flex scanner internal error--no action found" );
   } /* end of action switch */
      } /* end of scanning one token */
   } /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *   EOB_ACT_LAST_MATCH -
 *   EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *   EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
       register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
   register char *source = (yytext_ptr);
   register int number_to_move, i;
   int ret_val;

   if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
      YY_FATAL_ERROR(
      "fatal flex scanner internal error--end of buffer missed" );

   if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
      { /* Don't try to fill the buffer, so this is an EOF. */
      if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
         {
         /* We matched a single character, the EOB, so
          * treat this as a final EOF.
          */
         return EOB_ACT_END_OF_FILE;
         }

      else
         {
         /* We matched some text prior to the EOB, first
          * process it.
          */
         return EOB_ACT_LAST_MATCH;
         }
      }

   /* Try to read more data. */

   /* First move last chars to start of buffer. */
   number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

   for ( i = 0; i < number_to_move; ++i )
      *(dest++) = *(source++);

   if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
      /* don't do the read, it's not guaranteed to return an EOF,
       * just force an EOF
       */
      YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

   else
      {
         yy_size_t num_to_read =
         YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

      while ( num_to_read <= 0 )
         { /* Not enough room in the buffer - grow it. */

         /* just a shorter name for the current buffer */
         YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

         int yy_c_buf_p_offset =
            (int) ((yy_c_buf_p) - b->yy_ch_buf);

         if ( b->yy_is_our_buffer )
            {
            yy_size_t new_size = b->yy_buf_size * 2;

            if ( new_size <= 0 )
               b->yy_buf_size += b->yy_buf_size / 8;
            else
               b->yy_buf_size *= 2;

            b->yy_ch_buf = (char *)
               /* Include room in for 2 EOB chars. */
               yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
            }
         else
            /* Can't grow it, we don't own it. */
            b->yy_ch_buf = 0;

         if ( ! b->yy_ch_buf )
            YY_FATAL_ERROR(
            "fatal error - scanner input buffer overflow" );

         (yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

         num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
                  number_to_move - 1;

         }

      if ( num_to_read > YY_READ_BUF_SIZE )
         num_to_read = YY_READ_BUF_SIZE;

      /* Read in more data. */
      YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
         (yy_n_chars), num_to_read );

      YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
      }

   if ( (yy_n_chars) == 0 )
      {
      if ( number_to_move == YY_MORE_ADJ )
         {
         ret_val = EOB_ACT_END_OF_FILE;
         yyrestart(yyin  );
         }

      else
         {
         ret_val = EOB_ACT_LAST_MATCH;
         YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
            YY_BUFFER_EOF_PENDING;
         }
      }

   else
      ret_val = EOB_ACT_CONTINUE_SCAN;

   if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
      /* Extend the array by 50%, plus the number we really need. */
      yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
      YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
      if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
         YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
   }

   (yy_n_chars) += number_to_move;
   YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
   YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

   (yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

   return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
   register yy_state_type yy_current_state;
   register char *yy_cp;

   yy_current_state = (yy_start);

   for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
      {
      register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
      if ( yy_accept[yy_current_state] )
         {
         (yy_last_accepting_state) = yy_current_state;
         (yy_last_accepting_cpos) = yy_cp;
         }
      while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
         {
         yy_current_state = (int) yy_def[yy_current_state];
         }
      yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
      }

   return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *   next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
   register int yy_is_jam;
      register char *yy_cp = (yy_c_buf_p);
   register YY_CHAR yy_c = 1;
   if ( yy_accept[yy_current_state] )
      {
      (yy_last_accepting_state) = yy_current_state;
      (yy_last_accepting_cpos) = yy_cp;
      }
   while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
      {
      yy_current_state = (int) yy_def[yy_current_state];
      }
   yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
   yy_is_jam = (yy_current_state == 185);

      return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
   int c;
   *(yy_c_buf_p) = (yy_hold_char);

   if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
      {
      /* yy_c_buf_p now points to the character we want to return.
       * If this occurs *before* the EOB characters, then it's a
       * valid NUL; if not, then we've hit the end of the buffer.
       */
      if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
         /* This was really a NUL. */
         *(yy_c_buf_p) = '\0';

      else
         { /* need more input */
         yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
         ++(yy_c_buf_p);

         switch ( yy_get_next_buffer(  ) )
            {
            case EOB_ACT_LAST_MATCH:
               /* This happens because yy_g_n_b()
                * sees that we've accumulated a
                * token and flags that we need to
                * try matching the token before
                * proceeding.  But for input(),
                * there's no matching to consider.
                * So convert the EOB_ACT_LAST_MATCH
                * to EOB_ACT_END_OF_FILE.
                */

               /* Reset buffer status. */
               yyrestart(yyin );

               /*FALLTHROUGH*/

            case EOB_ACT_END_OF_FILE:
               {
               if ( yywrap( ) )
                  return EOF;

               if ( ! (yy_did_buffer_switch_on_eof) )
                  YY_NEW_FILE;
#ifdef __cplusplus
               return yyinput();
#else
               return input();
#endif
               }

            case EOB_ACT_CONTINUE_SCAN:
               (yy_c_buf_p) = (yytext_ptr) + offset;
               break;
            }
         }
      }

   c = *(unsigned char *) (yy_c_buf_p);   /* cast for 8-bit char's */
   *(yy_c_buf_p) = '\0';   /* preserve yytext */
   (yy_hold_char) = *++(yy_c_buf_p);

   return c;
}
#endif   /* ifndef YY_NO_INPUT */

/**
 * Immediately switch to a different input stream.
 *
 * @param input_file
 *    A readable stream.
 *
 * @note
 *    This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
   if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
      YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
   }

   yy_init_buffer(YY_CURRENT_BUFFER,input_file );
   yy_load_buffer_state( );
}

/**
 * Switch to a different input buffer.
 *
 * @param new_buffer
 *    The new input buffer.
 *
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
   /* TODO. We should be able to replace this entire function body
    * with
    *      yypop_buffer_state();
    *      yypush_buffer_state(new_buffer);
    */

   yyensure_buffer_stack ();
   if ( YY_CURRENT_BUFFER == new_buffer )
      return;

   if ( YY_CURRENT_BUFFER )
      {
      /* Flush out information for old buffer. */
      *(yy_c_buf_p) = (yy_hold_char);
      YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
      YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
      }

   YY_CURRENT_BUFFER_LVALUE = new_buffer;
   yy_load_buffer_state( );

   /* We don't actually know whether we did this switch during
    * EOF (yywrap()) processing, but the only time this flag
    * is looked at is after yywrap() is called, so it's safe
    * to go ahead and always set it.
    */
   (yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
       (yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
   (yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
   yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
   (yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 *
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
   YY_BUFFER_STATE b;

   b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
   if ( ! b )
      YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

   b->yy_buf_size = size;

   /* yy_ch_buf has to be 2 characters longer than the size given because
    * we need to put in 2 end-of-buffer characters.
    */
   b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
   if ( ! b->yy_ch_buf )
      YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

   b->yy_is_our_buffer = 1;

   yy_init_buffer(b,file );

   return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 *
 */

void yy_delete_buffer (YY_BUFFER_STATE  b )
{

   if ( ! b )
      return;

   if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
      YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

   if ( b->yy_is_our_buffer )
      yyfree((void *) b->yy_ch_buf  );

   yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
   int oerrno = errno;

   yy_flush_buffer(b );

   b->yy_input_file = file;
   b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;

   errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 *
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
       if ( ! b )
      return;

   b->yy_n_chars = 0;

   /* We always need two end-of-buffer characters.  The first causes
    * a transition to the end-of-buffer state.  The second causes
    * a jam in that state.
    */
   b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
   b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

   b->yy_buf_pos = &b->yy_ch_buf[0];

   b->yy_at_bol = 1;
   b->yy_buffer_status = YY_BUFFER_NEW;

   if ( b == YY_CURRENT_BUFFER )
      yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
       if (new_buffer == NULL)
      return;

   yyensure_buffer_stack();

   /* This block is copied from yy_switch_to_buffer. */
   if ( YY_CURRENT_BUFFER )
      {
      /* Flush out information for old buffer. */
      *(yy_c_buf_p) = (yy_hold_char);
      YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
      YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
      }

   /* Only push if top exists. Otherwise, replace top. */
   if (YY_CURRENT_BUFFER)
      (yy_buffer_stack_top)++;
   YY_CURRENT_BUFFER_LVALUE = new_buffer;

   /* copied from yy_switch_to_buffer. */
   yy_load_buffer_state( );
   (yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *
 */
void yypop_buffer_state (void)
{
       if (!YY_CURRENT_BUFFER)
      return;

   yy_delete_buffer(YY_CURRENT_BUFFER );
   YY_CURRENT_BUFFER_LVALUE = NULL;
   if ((yy_buffer_stack_top) > 0)
      --(yy_buffer_stack_top);

   if (YY_CURRENT_BUFFER) {
      yy_load_buffer_state( );
      (yy_did_buffer_switch_on_eof) = 1;
   }
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
   yy_size_t num_to_alloc;

   if (!(yy_buffer_stack)) {

      /* First allocation is just for 2 elements, since we don't know if this
       * scanner will even need a stack. We use 2 instead of 1 to avoid an
       * immediate realloc on the next call.
         */
      num_to_alloc = 1;
      (yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
                        (num_to_alloc * sizeof(struct yy_buffer_state*)
                        );
      if ( ! (yy_buffer_stack) )
         YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

      memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

      (yy_buffer_stack_max) = num_to_alloc;
      (yy_buffer_stack_top) = 0;
      return;
   }

   if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

      /* Increase the buffer to prepare for a possible push. */
      int grow_size = 8 /* arbitrary grow size */;

      num_to_alloc = (yy_buffer_stack_max) + grow_size;
      (yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
                        ((yy_buffer_stack),
                        num_to_alloc * sizeof(struct yy_buffer_state*)
                        );
      if ( ! (yy_buffer_stack) )
         YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

      /* zero only the new slots.*/
      memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
      (yy_buffer_stack_max) = num_to_alloc;
   }
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 *
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
   YY_BUFFER_STATE b;

   if ( size < 2 ||
        base[size-2] != YY_END_OF_BUFFER_CHAR ||
        base[size-1] != YY_END_OF_BUFFER_CHAR )
      /* They forgot to leave room for the EOB's. */
      return 0;

   b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
   if ( ! b )
      YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

   b->yy_buf_size = size - 2;   /* "- 2" to take care of EOB's */
   b->yy_buf_pos = b->yy_ch_buf = base;
   b->yy_is_our_buffer = 0;
   b->yy_input_file = 0;
   b->yy_n_chars = b->yy_buf_size;
   b->yy_is_interactive = 0;
   b->yy_at_bol = 1;
   b->yy_fill_buffer = 0;
   b->yy_buffer_status = YY_BUFFER_NEW;

   yy_switch_to_buffer(b  );

   return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 *
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{

   return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 *
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
   YY_BUFFER_STATE b;
   char *buf;
   yy_size_t n;
   yy_size_t i;

   /* Get memory for full buffer, including space for trailing EOB's. */
   n = _yybytes_len + 2;
   buf = (char *) yyalloc(n  );
   if ( ! buf )
      YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

   for ( i = 0; i < _yybytes_len; ++i )
      buf[i] = yybytes[i];

   buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

   b = yy_scan_buffer(buf,n );
   if ( ! b )
      YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

   /* It's okay to grow etc. this buffer, and we should throw it
    * away when we're done.
    */
   b->yy_is_our_buffer = 1;

   return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
       (void) fprintf( stderr, "%s\n", msg );
   exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
   do \
      { \
      /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
      yytext[yyleng] = (yy_hold_char); \
      (yy_c_buf_p) = yytext + yyless_macro_arg; \
      (yy_hold_char) = *(yy_c_buf_p); \
      *(yy_c_buf_p) = '\0'; \
      yyleng = yyless_macro_arg; \
      } \
   while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 *
 */
int yyget_lineno  (void)
{

    return yylineno;
}

/** Get the input stream.
 *
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 *
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 *
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 *
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 *
 */
void yyset_lineno (int  line_number )
{

    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 *
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{

    /* Pop the buffer stack, destroying each element. */
   while(YY_CURRENT_BUFFER){
      yy_delete_buffer(YY_CURRENT_BUFFER  );
      YY_CURRENT_BUFFER_LVALUE = NULL;
      yypop_buffer_state();
   }

   /* Destroy the stack itself. */
   yyfree((yy_buffer_stack) );
   (yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
   register int i;
   for ( i = 0; i < n; ++i )
      s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
   register int n;
   for ( n = 0; s[n]; ++n )
      ;

   return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
   return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
   /* The cast to (char *) in the following accommodates both
    * implementations that use char* generic pointers, and those
    * that use void* generic pointers.  It works with the latter
    * because both ANSI C and C++ allow castless assignment from
    * any pointer type to void*, and deal with argument conversions
    * as though doing an assignment.
    */
   return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
   free( (char *) ptr );   /* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

